/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'tiktok' : null } |
  { 'instagram' : null } |
  { 'twitterX' : null } |
  { 'facebook' : null } |
  { 'youtube' : null } |
  { 'telegram' : null };
export interface NewOrderRequest {
  'service' : bigint,
  'link' : string,
  'quantity' : bigint,
}
export type T = { 'canceled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'refunded' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export interface T__1 {
  'id' : bigint,
  'minOrder' : bigint,
  'name' : string,
  'pricePer1000' : bigint,
  'description' : string,
  'category' : Category,
  'maxOrder' : bigint,
}
export interface T__2 {
  'id' : bigint,
  'service' : bigint,
  'status' : T,
  'link' : string,
  'createdAt' : Time,
  'user' : Principal,
  'totalCost' : bigint,
  'quantity' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add funds to a user's balance. Admin only.
   */
  'addBalance' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Get the caller's current balance. Requires user role.
   */
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get a specific order by ID. Only the order owner or an admin can view it.
   */
  'getOrderById' : ActorMethod<[bigint], T__2>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List all orders for a given user. Only the user themselves or an admin can list orders.
   */
  'listOrdersByUser' : ActorMethod<[Principal], Array<T__2>>,
  /**
   * / List all available SMM services. Public - no auth required.
   */
  'listServices' : ActorMethod<[], Array<T__1>>,
  /**
   * / Place a new SMM order. Requires user role.
   */
  'placeOrder' : ActorMethod<[NewOrderRequest], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Update an order's status. Admin only.
   */
  'updateOrderStatus' : ActorMethod<[bigint, T], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];