/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const T = IDL.Variant({
  'canceled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const T__2 = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Nat,
  'status' : T,
  'link' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'totalCost' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const TopUpInitiation = IDL.Record({
  'redirectUrl' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Category = IDL.Variant({
  'tiktok' : IDL.Null,
  'instagram' : IDL.Null,
  'twitterX' : IDL.Null,
  'facebook' : IDL.Null,
  'youtube' : IDL.Null,
  'telegram' : IDL.Null,
});
export const T__1 = IDL.Record({
  'id' : IDL.Nat,
  'minOrder' : IDL.Nat,
  'name' : IDL.Text,
  'pricePer1000' : IDL.Float64,
  'description' : IDL.Text,
  'category' : Category,
  'maxOrder' : IDL.Nat,
});
export const NewOrderRequest = IDL.Record({
  'service' : IDL.Nat,
  'link' : IDL.Text,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'addBalanceToUser' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [T__2], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initiateTopUp' : IDL.Func([TopUpInitiation], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listOrdersByUser' : IDL.Func([IDL.Principal], [IDL.Vec(T__2)], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
  'placeOrder' : IDL.Func([NewOrderRequest], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, T], [], []),
  'updateServicePrice' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const T = IDL.Variant({
    'canceled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const T__2 = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Nat,
    'status' : T,
    'link' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'totalCost' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const TopUpInitiation = IDL.Record({
    'redirectUrl' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Category = IDL.Variant({
    'tiktok' : IDL.Null,
    'instagram' : IDL.Null,
    'twitterX' : IDL.Null,
    'facebook' : IDL.Null,
    'youtube' : IDL.Null,
    'telegram' : IDL.Null,
  });
  const T__1 = IDL.Record({
    'id' : IDL.Nat,
    'minOrder' : IDL.Nat,
    'name' : IDL.Text,
    'pricePer1000' : IDL.Float64,
    'description' : IDL.Text,
    'category' : Category,
    'maxOrder' : IDL.Nat,
  });
  const NewOrderRequest = IDL.Record({
    'service' : IDL.Nat,
    'link' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'addBalanceToUser' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [T__2], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initiateTopUp' : IDL.Func([TopUpInitiation], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listOrdersByUser' : IDL.Func([IDL.Principal], [IDL.Vec(T__2)], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
    'placeOrder' : IDL.Func([NewOrderRequest], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, T], [], []),
    'updateServicePrice' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };